<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/forms.css'); ?>
		<?= $this->jQuery(); ?>
		<script type="text/javascript" src="/js/imjob/forms/js.js" ></script>
	</head>
	<body>
		<div id="header">
			<div id="site-toolbar">
				<div id="socialbookmark-icons">
					<img src="/images/socialbookmarks/feed.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/twitter.png" alt="Follows us on Twitter" title="Follows us on Twitter" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/stumble.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/technorati.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/delicious.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/email.png" alt="Email this page to a friend" title="Email this page to a friend" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/facebook.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/furl.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/linkedin.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/newsvine.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/posterous.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/reddit.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/stumble.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
					<img src="/images/socialbookmarks/sphinn.png" alt="Subscribe to our RSS" title="Subscribe to our RSS" class="socialbookmark-icon" />
				</div>				
				<?= $this->render('LoginLogoutPanel.phtml'); ?>
			</div>
			<div id="logo-div">
				<img src="/images/theme/logo.png" id="logo" />
				<h4>Nexus for job seekers, employer and employment agencies</h4>
			</div>
			
			
			<div id="navigation">
				<ul>
					<li><a href="/">Home</a>
					<li><a href="/JobSeeker/">Job Seekers</a></li>
					<li><a href="/Employer/">Employers</a></li>
					<!--  <li><a href="/EmploymentAgency/">Employment Agencies</a></li> -->
				</ul>
			</div>
		</div>
		
		<div id="content">
			<div id="flash-messages" style="display:<?= ( (is_array($this->messages) && !empty($this->messages)) ?"block":"none")?>;">
				<img src="/images/icons/cancel_16.png" style="float:right;cursor:pointer;" onclick='$("#flash-messages").fadeOut(500);'/>
				<ul id="flash-messages-ul">
					<?php 
					foreach($this->messages as $message)
					{
						echo '<li><b>'.$message.'</b></li>';
					}
					?>
				</ul>
			</div>
			<br/>
			<?= $this->layout()->content; ?>
		</div>
		<div id="footer">
			<ul>
				<li><a href="">About us</a></li>
				<li><a href="">Privacy Policy</a></li>
				<li><a href="">Terms and Conditions</a></li>
			</ul>
			&copy; <?= date('Y'); ?> ImJob.org 
		</div>
	</body>
</html>
