<div style='padding:20px;'>
	<h1 style="text-align:center;">Thank you <?= $this->escape($this->user->getDisplayName()); ?></h1>
	<br/><br/>
	
	<h3>Just one more step</h3>
	
	
	An email has been sent to your <b>email address with instructions on how to activate your account</b>.<br/>
	The email sent is valid for next 48 hours, otherwise you would need to register again.<br/>
	Please check your mailbox and <b>activite your account now</b>.<br/><br/>
	
	
	Should you face any technical problem, please feel free to contact us.<br/>
	
	<b>Thanks again</b>
</div>